apiVersion: v1
kind: Pod
metadata:
  name: proxy
  namespace: {{ $.Release.Namespace }}
  labels:
    app: proxy
spec:
  containers:
  - name: proxy
    image: multiversx/chain-proxy
    args: ["--config=/mx-chain-proxy-go/cmd/proxy/proxy-config/config.toml"]
    volumeMounts:
    - name: config
      mountPath: "/mx-chain-proxy-go/cmd/proxy/proxy-config"
      readOnly: true
  volumes:
  - name: config
    configMap:
      name: proxy-config
      items:
      - key: "config.toml"
        path: "config.toml"
