apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    app: proxy
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    type: {{ $.Values.proxyService.type }}
